name: score_volei_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0" # Atualiza isso, se estiver diferente


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adicionando a fonte corretamente
  fonts:
    - family: Digital7
      fonts:
        - asset: assets/fonts/digital-7.ttf

  assets:
    - assets/fonts/digital-7.ttf
